#schema: https://www.schemastore.org/typst.json
[package]
name = "gruvbox"
entrypoint = "lib.typ"
version = "1.0.0"
authors = ["@arsmoriendy"]
license = "GPL-3.0-only"
description = "Gruvbox colors."
