#schema: https://www.schemastore.org/typst.json
[package]
name = "gruvbox"
entrypoint = "lib.typ"
version = "1.0.0"
authors = ["@arsmoriendy"]
license = "MIT"
description = "Gruvbox colors."
exclude = ["./examples/main.pdf"]
